### ISSUE TITLE
Error: cannot find module 'yeoman generator'

### ISSUE THREAD

**Issue by anwather** [BrianFarnhill/generator-arm-template#2]
I have installed the template generator however when I do
```powershell 
yo arm-template
```
it throws an error saying it can't find the yeoman generator.

```powershell
PS C:\windows\system32> yo arm-template
module.js:538
    throw err;
    ^

Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-arm-template\generators\app
\index.js:2:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by anwather** [comment]
Nevermind - the below fixed it good
```powershell
npm install -g yeoman-generator
```
